logging:
  level:
    root: INFO
    com.rahul: ERROR
  file:
#    name: logs/spring-boot-logger.log                                                                                  To save file in same project
    name: P://logs/spring-boot-logger.log
    max-size: 10MB
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1}): %msg%n%throwable"
    file: "%d %p %C{1} [%t] %m%n"
  path: P://logs
  rollingPolicy:
    timeBased:
      fileNamePattern: ${LOGS}/archived/spring-boot-logger-%d{yyyy-MM-dd}.%i.log
#      file-name-pattern: logs/archived/spring-boot-logger-%d{yyyy-MM-dd}.%i.log                                        To save file in same project
